# Site settings
title: iMoneza Documentation
baseurl: /documentation

# Build settings
markdown: kramdown
exclude: ['README.md']
sass:
    sass_dir: _sass

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"